Added LABIOS and necessary figures
grc-iit/grc-iit.github.io pull request #5
Opened 2023-11-10 00:40 UTC by nrj5k

2023-11-10 06:50 UTC, izzet requested changes

2023-11-10 06:50 UTC, izzet commented on src/pages/research/projects/labios.mdx
> +title: "LABIOS: A Distributed\\Label-Based I/O System"
Fix `\\` please.

2023-11-10 06:50 UTC, izzet commented on docusaurus.config.js
> +		label: "Labios",
Is this a featured project?

2023-11-11 15:24 UTC, nrj5k commented
fixed.

and its the core project dtio is behind so i dunno, prolly anthony would
know better

On Fri, Nov 10, 2023 at 12:51 AM Izzet Yildirim ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/pages/research/projects/labios.mdx
> <https://github.com/grc-iit/grc-iit.github.io/pull/5#discussion_r1388986443>
> :
>
> > @@ -0,0 +1,109 @@
> +---
> +title: "LABIOS: A Distributed\\Label-Based I/O System"
>
> Fix \\ please.
> ------------------------------
>
> In docusaurus.config.js
> <https://github.com/grc-iit/grc-iit.github.io/pull/5#discussion_r1388989118>
> :
>
> > @@ -200,6 +200,10 @@ const config = {
>                  label: "ChronoLog",
>                  to: "/research/projects/chronolog",
>                },
> +	      {
> +		label: "Labios",
>
> Is this a featured project?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/grc-iit/grc-iit.github.io/pull/5#pullrequestreview-1724131923>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACPJLX5WTBPQ5QKK3W2767TYDXFFJAVCNFSM6AAAAAA7FNDWROVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRUGEZTCOJSGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-14 00:12 UTC, merged